### ISSUE TITLE
Python2?

### ISSUE THREAD

**Issue by divined** [wodby/node#5]
A lot of node modules requires python2. For example node-gyp. Why you didn't add it?
Can you add it?

**Comment by csandanov** [comment]
Now added `-dev` image variants with dev packages installed (currently only python2) and full sudo

**Comment by divined** [comment]
Thx man, awesome job

**Comment by divined** [comment]
But
make: g++: Command not found (((

**Comment by csandanov** [comment]
Do you have a list of dependencies required by some popular node package? so we could add everything needed

**Comment by divined** [comment]
No, I don't (
Only use suggestions from the users.

**Comment by csandanov** [comment]
What package are you installing? I've installed `node-gyp` without any issues
