### ISSUE TITLE
sudo seem to not work on dev images

### ISSUE THREAD

**Issue by walkero-gr** [wodby/node#6]
I use the 12 dev image and I try to use sudo to edit /etc/hosts file, but it asks for password for the wodby user. Tried to continue without password, or with 'wodby', but it didn't work. How can I overcome this issue?

I tested the following image tags
12-dev-0.34.3
12-dev-0.33.1

**Comment by csandanov** [comment]
Thank you for reporting, there was a bug, it fixed now in latest and 0.34.5
