### ISSUE TITLE
g++

### ISSUE THREAD

**Issue by gene-miller** [wodby/node#8]
Hi guys,

I hit the following error when running an `npm install` on a new Drupal Radix 5.x based theme (https://www.drupal.org/project/radix):

```
make: g++: No such file or directory make
```
Solved by installing g++ in the node container

```
apk add g++
```

Maybe something you would consider adding to the container?
Cheers!

**Comment by csandanov** [comment]
yes, we could add this, could you please share what's npm package that requires the `g++`? or maybe what's the theme if it's public

**Comment by gene-miller** [comment]
Thanks Chingis, 

Theme is a fresh radix subtheme: Radix (https://www.drupal.org/project/radix)

Command to generate subtheme:
```
drush --include="themes/contrib/radix" radix:create SUBTHEME_NAME"
```

Looks like `libsass` is the package that requires g++
Error:
```
make: g++: No such file or directory
make: *** [src/libsass.target.mk:162: Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
``
